services:

  app:
    build: .
    command: gunicorn -b 0.0.0.0:8000 app.app:app
    env_file:
      - .env
    image: app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./sample_input:/app/sample_input

networks:
  app-network:
    driver: bridge
