services:

  app:
    build: .
    command: flask --app app/app.py run --debug
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app
          ignore:
            - .venv
